APP_GATEWAY_NOTIFICATION_PORT = 51005
APP_GATEWAY_QUERY_PORT = 51006

DEFAULT_GATEWAY_NOTIFICATION_SOCKET_STRING = f"tcp://127.0.0.1:{APP_GATEWAY_NOTIFICATION_PORT}"
DEFAULT_GATEWAY_QUERY_SOCKET_STRING = f"tcp://127.0.0.1:{APP_GATEWAY_QUERY_PORT}"
